name: release

on:
  push:
    tags:
      - v*

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.8]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Download Build Tools for Visual Studio 2019
      run: Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

    - name: Run vs_buildtools.exe install
      run: >-
        ./vs_buildtools.exe --quiet --wait --norestart --nocache
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
        --add Microsoft.VisualStudio.Component.VC.v141.x86.x64
        --add Microsoft.VisualStudio.Component.VC.140
        --includeRecommended

    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install Python package dependencies
      run: pip install cython wheel

    - name: Build binary wheel
      run: python setup.py bdist_wheel

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-${{ matrix.python-version }}-${{ matrix.architecture }}
        path: dist

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    strategy:
      max-parallel: 3
      matrix:
        python-version:
          - cp38-cp38

    steps:
      - uses: actions/checkout@master

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install Python package dependencies
        run: /opt/python/${{ matrix.python-version }}/bin/python -m pip install -r requirements.txt

      - name: Build binary wheel
        run: /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel

      - name: Apply auditwheel
        run: auditwheel repair -w dist dist/*

      - name: Remove linux wheel
        run: rm dist/*-linux_x86_64.whl

      - name: Install package
        run: /opt/python/${{ matrix.python-version }}/bin/python -m pip install dist/*

      - name: Remove xlsxio
        run: rm -rf xlsxio

      - name: Run tests
        run: /opt/python/${{ matrix.python-version }}/bin/python -m pytest

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist-linux-${{ matrix.python-version }}
          path: dist
