name: release-linux

on:
  push:
    branches:
        - feature/build-all

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    strategy:
      max-parallel: 3
      matrix:
        python-version:
          - cp38-cp38

    steps:
      - uses: actions/checkout@master

      - name: Install Python package dependencies
        run: /opt/python/${{ matrix.python-version }}/bin/python -m pip install cython wheel

      - name: Build binary wheel
        run: /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel

      - name: Apply auditwheel
        run: auditwheel repair -w dist dist/*

      - name: Remove linux wheel
        run: rm dist/*-linux_x86_64.whl

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist-linux-${{ matrix.python-version }}
          path: dist
